[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.1"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.1"

[[constraint]]
  name = "github.com/golang/snappy"
  version = "0.0.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"

[[constraint]]
  name = "github.com/mongodb/mongo-tools"
  version = "r4.0.9"

[[constraint]]
  name = "github.com/mongodb/mongo-tools-common"
  version = "0.0.0"

[[constraint]]
  name = "github.com/otiai10/copy"
  version = "1.0.1"

[[constraint]]
  name = "github.com/pierrec/lz4"
  version = "2.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/prometheus/common"
  version = "0.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.0"

[[constraint]]
  name = "github.com/theckman/go-flock"
  version = "0.7.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.19.1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
