version: "3"
services:
  cfg01:
    image: mongo:3.6
    hostname: cfg01
    command: mongod --configsvr --replSet cfg --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/cfg_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile
  cfg02:
    image: mongo:3.6
    hostname: cfg02
    command: mongod --configsvr --replSet cfg --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/cfg_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile
  cfg03:
    image: mongo:3.6
    hostname: cfg03
    command: mongod --configsvr --replSet cfg --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/cfg_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile
      
  rs101:
    image: mongo:3.6
    hostname: rs101
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/rs1_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile
  rs102:
    image: mongo:3.6
    hostname: rs102
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/rs1_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile
  rs103:
    image: mongo:3.6
    hostname: rs103
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/rs1_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile

  rs201:
    image: mongo:3.6
    hostname: rs201
    command: mongod --replSet rs2 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/rs1_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile
  rs202:
    image: mongo:3.6
    hostname: rs202
    command: mongod --replSet rs2 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/rs1_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile
  rs203:
    image: mongo:3.6
    hostname: rs203
    command: mongod --replSet rs2 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/rs1_init.js:/docker-entrypoint-initdb.d/02_init.js
      - ./keyFile:/opt/keyFile

  mongos:
    image: mongo:3.6
    hostname: mongos
    command: mongos --port 27017 --configdb cfg/cfg01:27017,cfg02:27017,cfg03:27017
    # ports:
    #   - "27017:27017"
    volumes:
      - ./scripts/01_usrs.sh:/docker-entrypoint-initdb.d/01_users.sh
      - ./scripts/sharded/mongos_init.js:/docker-entrypoint-initdb.d/02_init.js
      # - ./keyFile:/opt/keyFile
    depends_on:
      - cfg01
      - cfg02
      - cfg03
      - rs101
      - rs102
      - rs103
      - rs201
      - rs202
      - rs203